journals:
  - openjournals/joss-reviews-biohackrxiv:
      editor_team_id: biohackrxiv
      eics:
        - http://thebird.nl/
      editors:
        - https://github.com/alexgarciac
        - https://github.com/ljgarcia
      papers: openjournals/joss-papers-biohackrxiv
      reviewers: nil
      reviewers_signup: nil
      site_host: https://test.osf.io/preprints/biohackrxiv
      doi_prefix: "10.xxxx"
      journal_alias: biohackrxiv
      journal_launch_date: '2020-01-01'
      site_name: BioHackrXiv
      donate_url: https://cos.io/donate
      site_api_key: nil
